language: python

dist: xenial

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

install:
  - pip install .[test,wordlist]

script:
  - coverage run -m unittest tests --quiet
  - coverage report --show-missing
  - codecov

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "heDhlQiAEnH/aqflHnaC/pN4HYNKm0lDevN6BkYgAYz1WesKs/PgC8zogVfTpyvpiAAdQkL97Ch8+jlYc0NdcnwKo30TEV20Ksl5X6u7TXlllm3555Zrqc5n2MrfrSlDfoNQQuE2COv+x2HZxFbcHbLDMsg5XCpHQCpL8D8gkc5mbk0Y+tMWXYA+kvWcnxOv+/NfUW4EAtsddJ4zMYW+1w1o7lN9NXg2moZ5x0aclo/jo8xYszOw5KAAThQZNCRIHGvzclbQd9TSYcoVnWsbJwgHq+oiyCbH91DaPefMMFFRu2qfTmMf8x8mq3sFBeBpO3cC9T2yOUkbLg2BXCnyH30/S0gAfLoMu/TNcfLbt8TYiOGcLb1whUSqpRljZqry2yzwi1VQV1MmRUGs4xDRpivthiTKYbe1zTm3mexUikQEvX7YM2b3NOK9gjLstOJo2+YsW3kL8qAvwievPP6fRm4juMKmxtaJAmZtTkA/XI9KCfFCYhG7gHWFCIk6BOVfV/lGEpwVRd1cb/tnaPWeQIuXpqBuDf0boSYHq4VwptRejW6HlXlO/jOexEFracxWPvxzARNDhO9TO1MbUZPGUGDNqjm4xvv5daazCA9FZ0GyQKBJ9huNVMYwacuYgoev4ixaGABMuCWwoeyGwlcBdBXC9XVN2XN7UlSYkw4Ne1Q="
  skip_existing: true
  on:
    tags: true
